### ISSUE TITLE
Restarts when changing from Day to Night using MQTT

### ISSUE THREAD

**Issue by CAB426** [thanksmister/android-mqtt-alarm-panel#120]
Hello,

 When I change from Day to Night mode using MQTT (below_horizon), I am seeing the app continuously restart (recreate).  It continues until I send the day command (above_horizon) at which point the restarts stop, however it stays in night mode and no longer responds to MQTT commands (Day/Night).  If I restart the application, it will pick up the retained above_horizon and switch back to day mode.  However, if I start the application with below_horizon retained, the same behavior is seen (constant restarts).

Someone else mentioned they are seeing something similar here: https://github.com/thanksmister/android-mqtt-alarm-panel/issues/109#issuecomment-562427122

I am using a Fire HD 8 running Lineage OS 14.1 (1.9-r2), Mosquitto Server, and Home Assistant automations for the MQTT messages (but was testing manually as well).  I am running MQTT Alarm Panel v0.8.7-beta.4.

My settings are as follows:
Use Night mode = True

I have tried to turn on/off the ability for the app to adjust display settings.  
I have tried to turn on/off adaptive brightness in settings.

Please let me know if there are any other troubleshooting steps you would like me to take.

EDIT: I have also returned my Fire HD 8 to stock and tried there, same results.

Thanks,

CAB426

**Comment by austwhite** [comment]
I am having the same issue, but not isolated to just sending night mode.
If I have an automation set to check the sun status as per the instruction online.
```
- id: '1576985936474'
  alias: Alarm Panel - Sun
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: "{'sun':'{{states('sun.sun')}}'}"
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
```
Whenever the automation triggers and sends the current sun status, the Alarm Panel screen constantly refreshes and continues doing so until the app is terminated and restarted.
This makes the app unusable when using this function.

**Comment by thanksmister** [comment]
Sounds to me as though you are constantly sending MQTT messages to the application.  You can check the MQTT logs in the application settings to see how many times it is receiving MQTT messages and which ones it is receiving.

**Comment by austwhite** [comment]
Checked that.
It only sends the message once every 30 minutes. As per the automation.
Killing the app and restarting stops the flashing until the next time the automation triggers.
So once every 30 minutes I would need to kill the app to stop the flashing.
It only does it when the sun command is sent.  If that is removed, it never flashes if only the MQTT weather is used, using the same 30 minute interval.

**Comment by nickjedl** [comment]
Same issue here!

**Comment by vasylkuzenko** [comment]
Same issue here

**Comment by vasylkuzenko** [comment]
i think need set qos 0 or 2 (not 1) in automation. this resolved my problem 
```

- alias: mqtt_sun
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
    service: mqtt.publish
    data:
      payload_template:  >-
        {'sun':'{{states('sun.sun')}}'}
      retain: false
      qos: 0
      topic: alarmpanel/command
```
