### ISSUE TITLE
App doesn't follow custom state topic

### ISSUE THREAD

**Issue by nickjedl** [thanksmister/android-mqtt-alarm-panel#121]
Hello everyone

I am trying to set up the app, but it's not following the state topic at all. Currently the app says it's _Armed Home_ when it's actually _Disarmed_.
Also when I were to set Home Assistant to _Armed Away_ now, the app will still say it's _armed home_.
I can still issue commands which Home Assistant will follow, so the cmnd topic works, but everything related to the state topic doesn't.

This is my config:
```yaml
alarm_control_panel:
  - platform: manual_mqtt
    name: house_alarm
    code: !secret alarm_code
    state_topic: stat/house_alarm
    command_topic: cmnd/house_alarm
```
And this is the app: https://i.imgur.com/iNQaiAe.jpg
Looks correct to me.

What am I doing wrong?

**Comment by thanksmister** [comment]
I am using a custom command and state topic but I do not know what issue you are facing.  Try it without the code and name values for now, do not forget the rest of the setup.

```
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30
```
