### ISSUE TITLE
Don't switch back from Night to Day mode

### ISSUE THREAD

**Issue by goldandy** [thanksmister/android-mqtt-alarm-panel#123]
Hi there
I have a fire 7 with HA configured at Raspberry. APP is a last version from Play market.
When app receiving below_horizon MQTT message, it's going into Night mode as expected. 
After that, if I try to send above_horizon messages, nothing changed, App still in night mode
I tried to use same automation script and change only MQTT message. 
Tried with retain=false and qos=0, doesn't help
Any ideas?

**Comment by thanksmister** [comment]
I happen to have the exact same tablet and setup.  Here is the automation I use for HA to send above and below horizon to the app.  

```
- id: '1539017708085'
  alias: MQTT Sun
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
```

This is working well for me.   The app is not crashing right?  Or going into the background.   My Fire 7 likes to do that from time to time.
