### ISSUE TITLE
Please support other weather provider than DarkSky

### ISSUE THREAD

**Issue by ivanfor** [thanksmister/android-mqtt-alarm-panel#130]
**Is your feature request related to a problem?
DarkSky has stopped providing API keys :(

**Describe the solution you'd like**
An alternative. Another free weather provider would be great!

**Describe alternatives you've considered**
For example, OpenWeather map is free and offers a lot of information

**Comment by thanksmister** [comment]
Yeah, I have plans to make it more generic, so you can use any weather component with it.  For now the workaround is to format your own mqtt payload using values from whichever weather provider you are using:

{"topic": "alarmpanel/command","payload":"{'weather':{'summary':'Partly Cloudy','precipitation':'0','icon':'partly-cloudy-day','temperature':'22.5','units':'°C'}}

The part that may break is the icon, Darksky used specific icon values that are not the same as those found in the generic weather component. 

https://www.home-assistant.io/integrations/weather/

**Comment by ivanfor** [comment]
I'll try to do the "translation".
What would be the payload for the 3 day forecast?

**Comment by thanksmister** [comment]
That part may be going away, I have to see.  I have another implementation to port over from the Voice Panel project which just uses generic weather.  Not sure it has a forecast option.

**Comment by thanksmister** [comment]
The raw dump of darksky data looks like this

```
{'weather':{'temperature': 14.4, 'humidity': 88, 'ozone': 270.4, 'pressure': 1010.2, 'wind_bearing': 115, 'wind_speed': 12.2, 'visibility': 10.277, 'attribution': 'Powered by Dark Sky', 'forecast': [{'datetime': '2020-07-21T19:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.2, 'condition': 'cloudy'}, {'datetime': '2020-07-21T20:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-21T21:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-21T22:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-21T23:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-22T00:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-22T01:00:00+00:00', 'temperature': 14.4, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-22T02:00:00+00:00', 'temperature': 14.3, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-22T03:00:00+00:00', 'temperature': 14.1, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-22T04:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-22T05:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-22T06:00:00+00:00', 'temperature': 14.1, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-22T07:00:00+00:00', 'temperature': 14.2, 'precipitation': 0.5, 'condition': 'rainy'}, {'datetime': '2020-07-22T08:00:00+00:00', 'temperature': 14.2, 'precipitation': 0.7, 'condition': 'rainy'}, {'datetime': '2020-07-22T09:00:00+00:00', 'temperature': 14.2, 'precipitation': 0.8, 'condition': 'rainy'}, {'datetime': '2020-07-22T10:00:00+00:00', 'temperature': 14.1, 'precipitation': 0.8, 'condition': 'rainy'}, {'datetime': '2020-07-22T11:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.8, 'condition': 'rainy'}, {'datetime': '2020-07-22T12:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.8, 'condition': 'rainy'}, {'datetime': '2020-07-22T13:00:00+00:00', 'temperature': 14.1, 'precipitation': 0.7, 'condition': 'rainy'}, {'datetime': '2020-07-22T14:00:00+00:00', 'temperature': 14.3, 'precipitation': 0.5, 'condition': 'rainy'}, {'datetime': '2020-07-22T15:00:00+00:00', 'temperature': 14.6, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-22T16:00:00+00:00', 'temperature': 14.9, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-22T17:00:00+00:00', 'temperature': 15.2, 'precipitation': 0.5, 'condition': 'rainy'}, {'datetime': '2020-07-22T18:00:00+00:00', 'temperature': 15.4, 'precipitation': 0.6, 'condition': 'rainy'}, {'datetime': '2020-07-22T19:00:00+00:00', 'temperature': 15.3, 'precipitation': 0.5, 'condition': 'rainy'}, {'datetime': '2020-07-22T20:00:00+00:00', 'temperature': 15.2, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-22T21:00:00+00:00', 'temperature': 15, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-22T22:00:00+00:00', 'temperature': 15, 'precipitation': 0.2, 'condition': 'rainy'}, {'datetime': '2020-07-22T23:00:00+00:00', 'temperature': 15.0, 'precipitation': 0.2, 'condition': 'rainy'}, {'datetime': '2020-07-23T00:00:00+00:00', 'temperature': 14.9, 'precipitation': 0.2, 'condition': 'rainy'}, {'datetime': '2020-07-23T01:00:00+00:00', 'temperature': 14.7, 'precipitation': 0.1, 'condition': 'rainy'}, {'datetime': '2020-07-23T02:00:00+00:00', 'temperature': 14.5, 'precipitation': 0.1, 'condition': 'rainy'}, {'datetime': '2020-07-23T03:00:00+00:00', 'temperature': 14.2, 'precipitation': 0.1, 'condition': 'rainy'}, {'datetime': '2020-07-23T04:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.2, 'condition': 'rainy'}, {'datetime': '2020-07-23T05:00:00+00:00', 'temperature': 13.9, 'precipitation': 0.3, 'condition': 'rainy'}, {'datetime': '2020-07-23T06:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.4, 'condition': 'rainy'}, {'datetime': '2020-07-23T07:00:00+00:00', 'temperature': 14.1, 'precipitation': 0.5, 'condition': 'rainy'}, {'datetime': '2020-07-23T08:00:00+00:00', 'temperature': 14.0, 'precipitation': 0.6, 'condition': 'rainy'}, {'datetime': '2020-07-23T09:00:00+00:00', 'temperature': 13.9, 'precipitation': 0.9, 'condition': 'rainy'}, {'datetime': '2020-07-23T10:00:00+00:00', 'temperature': 13.8, 'precipitation': 1.3, 'condition': 'rainy'}, {'datetime': '2020-07-23T11:00:00+00:00', 'temperature': 13.6, 'precipitation': 1.8, 'condition': 'rainy'}, {'datetime': '2020-07-23T12:00:00+00:00', 'temperature': 13.5, 'precipitation': 2.0, 'condition': 'rainy'}, {'datetime': '2020-07-23T13:00:00+00:00', 'temperature': 13.6, 'precipitation': 1.8, 'condition': 'rainy'}, {'datetime': '2020-07-23T14:00:00+00:00', 'temperature': 13.8, 'precipitation': 1.8, 'condition': 'rainy'}, {'datetime': '2020-07-23T15:00:00+00:00', 'temperature': 14.0, 'precipitation': 1.9, 'condition': 'rainy'}, {'datetime': '2020-07-23T16:00:00+00:00', 'temperature': 14, 'precipitation': 1.4, 'condition': 'rainy'}, {'datetime': '2020-07-23T17:00:00+00:00', 'temperature': 13.9, 'precipitation': 0.8, 'condition': 'rainy'}, {'datetime': '2020-07-23T18:00:00+00:00', 'temperature': 13.7, 'precipitation': 0.6, 'condition': 'rainy'}, {'datetime': '2020-07-23T19:00:00+00:00', 'temperature': 13.4, 'precipitation': 0.6, 'condition': 'rainy'}], 'friendly_name': 'Dark Sky'}}
```

**Comment by derekatkins** [comment]
If I go to HASS and look up the Developer -> States of my weather.home, I get:
State: partlycloudy
and the following state attributes:
```yaml
temperature: 91
humidity: 48
pressure: 29.91
wind_bearing: 322.5
wind_speed: 0
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
forecast:
  - datetime: '2020-08-17T12:00:00-04:00'
    temperature: 88.2
    condition: partlycloudy
    pressure: 1015.8
    humidity: 57.5
    wind_speed: 8.3
    wind_bearing: 338.3
  - datetime: '2020-08-18T12:00:00-04:00'
    temperature: 89.2
    condition: partlycloudy
    pressure: 1014.5
    humidity: 52.1
    wind_speed: 4
    wind_bearing: 134.8
  - datetime: '2020-08-19T12:00:00-04:00'
    temperature: 85.1
    condition: rainy
    pressure: 1012.8
    humidity: 68.9
    wind_speed: 3.6
    wind_bearing: 97.9
  - datetime: '2020-08-20T12:00:00-04:00'
    temperature: 80.4
    condition: rainy
    pressure: 1013.2
    humidity: 78.3
    wind_speed: 10.4
    wind_bearing: 149.6
  - datetime: '2020-08-21T12:00:00-04:00'
    temperature: 81.7
    condition: rainy
    pressure: 1014.4
    humidity: 77.3
    wind_speed: 8.3
    wind_bearing: 173.2
friendly_name: Home
```
It would be nice if I could easily ship this off to the alarm panel.

**Comment by thanksmister** [comment]
@derekatkins I think we can do this but it would be easier to only support one day rather than the extended forecast from the weather component https://www.home-assistant.io/integrations/weather/.

**Comment by derekatkins** [comment]
@thanksmister I think "current weather" would probably be just fine, if you can't support the forecast.  

I didn't do anything special when configuring HA for the weather, so I took whatever weather component came by default in HassOS/4.11 / HA 0.113.  It is too bad the forecast data doesn't include the low temp, too, but that's not on you!  :)

**Comment by thanksmister** [comment]
Yeah, I know its not the best solution but it should make it more compatible rather than supporting every 3rd party component.  One issue I have with DarkSky is that that component used its own names for weather conditions, this should have been standard as well, or converted to fit the default weather component.

**Comment by derekatkins** [comment]
FYI, I changed my weather source to AccuWeather because the previous integration was providing bogus data (saying I was 90F when it was only 75).  Here's the current data I see now (which, surprise, includes low temp forecast too).  The weather.home state is "sunny" and the state attributes say:
```yaml
temperature: 75
humidity: 76
ozone: 75
pressure: 29.94
wind_bearing: 45
wind_speed: 2.2
visibility: 10
attribution: Data provided by AccuWeather
forecast:
  - datetime: '2020-08-18T11:00:00+00:00'
    temperature: 87
    templow: 69
    precipitation: 0
    precipitation_probability: 32
    wind_speed: 4.6
    wind_bearing: 84
    condition: lightning-rainy
  - datetime: '2020-08-19T11:00:00+00:00'
    temperature: 87
    templow: 67
    precipitation: 0.5
    precipitation_probability: 52
    wind_speed: 4.6
    wind_bearing: 112
    condition: lightning-rainy
  - datetime: '2020-08-20T11:00:00+00:00'
    temperature: 82
    templow: 67
    precipitation: 0.5
    precipitation_probability: 60
    wind_speed: 4.6
    wind_bearing: 146
    condition: lightning
  - datetime: '2020-08-21T11:00:00+00:00'
    temperature: 82
    templow: 67
    precipitation: 0.8
    precipitation_probability: 66
    wind_speed: 4.6
    wind_bearing: 131
    condition: lightning
  - datetime: '2020-08-22T11:00:00+00:00'
    temperature: 81
    templow: 68
    precipitation: 0.2
    precipitation_probability: 50
    wind_speed: 4.6
    wind_bearing: 215
    condition: lightning
friendly_name: Home
```
