### ISSUE TITLE
automation examples for weather and sun don't work (invalid configuration)

### ISSUE THREAD

**Issue by derekatkins** [thanksmister/android-mqtt-alarm-panel#133]
**Describe the bug**
I followed the documentation to create weather and sun automations from HA 0.113.2.  However, the proposed template is invalid.  My automation looks like:
```yaml
- id: mqtt_day_night
  alias: '[MQTT] Day/Night'
  trigger:
    platform: time_pattern
    minutes: '/30'
  #  condition: []
  action:
    service: mqtt.publish
    data:
      payload_template: {% raw %}"{'sun':'{{states('sun.sun')}}'}"{% endraw %}
      retain: true
      topic: alarmpanel/command
```
But when I "Check Configuration" if gives me the following error:
```
 Configuration invalid

                          Error loading /config/configuration.yaml: while scanning for the next token
found character '%' that cannot start any token
  in "/config/my_automations.yaml", line 163, column 26
```
Where "line 163" is the payload_template.  If I add single quotes around the raw and endraw portions then I get a different error:
```
 Configuration invalid

                          Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/my_automations.yaml", line 163, column 7
expected <block end>, but found '<scalar>'
  in "/config/my_automations.yaml", line 163, column 36
```
If I remove the raw and endraw then the configuration is accepted but I have no way to know if the alarm panel is getting the appropriate data.

**To Reproduce**
1. Apply automation as above (as documented)
2. Click on Check Configuration
3. See error

**Expected behavior**
I would have expected the example automation to work, or at least not be invalid yaml

**Smartphone (please complete the following information):**
 - Device: Amazon Fire 8
 - OS: current android
 - Browser [stock browser
 - Version: HA 0.113.2, alarm_panel 0.8.8.0

**Additional context**
Nothing, yet.

**Comment by derekatkins** [comment]
I can confirm that removing the raw / endraw pieces around the sun works:
```yaml
      payload_template: "{'sun':'{{states('sun.sun')}}'}"
```
When I use this payload template I get the following MQTT data:
```
{'sun':'above_horizon'}
```
.. which matches what the docs say I should expect.  For the weather, I think we'll need to update the docs once you fix Issue #130.

**Comment by thanksmister** [comment]
Yeah, you have to be really careful with quotes and yes, we are moving to a more generic weather implementation similar to what I have used in Voice Panel (which is not defunct because Snips sold out to Sonos). 

Here is what I have for my sun automation:

```
- id: '1539017708085'
  alias: MQTT Sun
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
```
