### ISSUE TITLE
Weather and Sun aren’t formatting correctly

### ISSUE THREAD

**Issue by scsmartt** [thanksmister/android-mqtt-alarm-panel#140]
**Describe the bug**
If I format the weather topic according to the instructions, it adds an extra ‘ around both sides of the “:”

If I format the sun topic according to the instructions, it won’t even publish, just gives me an error that payload_template requires string at data

**Comment by thanksmister** [comment]
You can test the template using the HA developer tools under template.  The quotes are always the issue. If it works in the developer tools, it will work in your automation.

**Comment by scsmartt** [comment]
> You can test the template using the HA developer tools under template. The quotes are always the issue. If it works in the developer tools, it will work in your automation.

**Comment by scsmartt** [comment]
I’ve been messing with it in developer tools with different formats and just can’t get it right. I didn’t know if changes in HA maybe broke the templates you have in the instructions. Any way you could post what you currently have in your automations.yaml config for each one?

**Comment by thanksmister** [comment]
```
payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
retain: true
topic: alarmpanel/command
```

I am just using this weather component: https://www.home-assistant.io/integrations/met/

```
payload_template: >-
  {'weather':{'condition':'{{states.weather.home.state}}','humidity':{{states.weather.home.attributes.humidity}},'temperature':{{states.weather.home.attributes.temperature}},'forecast':{{states.weather.home.attributes.forecast}}}}
retain: true
topic: alarmpanel/command
```

**Comment by scsmartt** [comment]
So when I add that to my weather automation, I get this:

Error loading /config/configuration.yaml: invalid key: "OrderedDict([('states.weather.home.attributes.humidity', None)])" in "/config/automations.yaml", line 24, column 0

**Comment by thanksmister** [comment]
The panel expects a certain format for weather, so you should pass in the weather settings with the format I provided.  If not, it may not work.  

 {'weather':{'condition':'{{states.weather.home.state}}','humidity':{{states.weather.home.attributes.humidity}},'temperature':{{states.weather.home.attributes.temperature}},'forecast':{{states.weather.home.attributes.forecast}}}}

**Comment by thanksmister** [comment]
I am not sure why, but everyone has issues with the sun.  There was a ticket about this yesterday, have a look at https://github.com/thanksmister/android-mqtt-alarm-panel/issues/139

**Comment by thanksmister** [comment]
here are my automations: 

```
- id: '1538595661244'
  alias: MQTT Weather
  trigger:
  - minutes: /15
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''weather'':{''condition'':''{{states.weather.home.state}}'',''humidity'':{{states.weather.home.attributes.humidity}},''temperature'':{{states.weather.home.attributes.temperature}},''forecast'':{{states.weather.home.attributes.forecast}}}}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
  mode: single
- id: '1539017708085'
  alias: MQTT Sun
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
```
