### ISSUE TITLE
With the demise of BWAlarm, Alarmo is showing to be an excellent replacement - now support is needed in Alarmpanel :-)

### ISSUE THREAD

**Issue by fribse** [thanksmister/android-mqtt-alarm-panel#148]
**Is your feature request related to a problem? Please describe.**
[Alarmo ](https://github.com/nielsfaber/alarmo) handles multiple users / codes and supports MQTT.
The code entered is sent via MQTT to Alarmo, and then alarmo will determine what to do with it, thus keeping information about which code/user is entered.
Alarmo is integrated like the builtin Home Assistant Alarm, so it has the usual states.

**Describe the solution you'd like**
Support for the Alarmo way of building the MQTT command/payload.

**Describe alternatives you've considered**
I could use wallpanel app with a dedicated lovelace view for alarms.

**Additional context**

**Comment by thanksmister** [comment]
I have looked at the integration.  We are already adding features that support most of the MQTT.  We attempted to update the Manual MQTT component with a PR but HA rejected our changes.  But most everything that you see in Alarmo MQTT can be done with automations as well.   In this way, a user does not have to use HACS or Alarmo to integrate with HA.   

You are welcome to try the new Alarm Panel beta which supports sensors and additional alarm states.   If you want to learn how we set up automations for enabling things like sending the code or sensors, you can join our discourse channel.

Discourse: https://discord.com/invite/euh9J2d
Beta: https://github.com/thanksmister/android-mqtt-alarm-panel/releases

**Comment by fribse** [comment]
> most everything that you see in Alarmo MQTT can be done with automations as well

How would I go about getting multiple pin's done with automations? I know the actions part is superfloues, which I've also told the developer, I don't think he should have those, he is thinking about doing a 'blueprints' package for those instead.
The GUI handling of sensors is brilliant, very easy to handle and for everybody to understand, I don't see that done in 'automations' either?

Have you suggested the extra state(s) to him? Niels sounds very interested in any input on this.
I've added myself to the discorde channel.

**Comment by thanksmister** [comment]
@derekatkins is is going to reach out to Alarmo developer to suggest some additional features for the MQTT communication.   We want to have additional states, we want some feedback when entering the wrong code, and few other improvements.  

I think with multiple pins, if we send a code like 1234, the automation needs to evaluate the code to see if its valid, and also it can associate the code with a user (matching it with a Alarmo user for example).    The payload might look like this:

```
{"command": "ARM_HOME", "code":1234}
```

So in the automation you have to parse out the "code" from the payload and manually compare it an existing code.  If it matches, then you can just use the alarm service to arm home.   

The new app also a status topic that will receive a payload VALID/INVALID if you want to display a notification in the app when the code is INVALID due to no match.   

In the new application we have an additional section that allows you to add up to for sensor topics with known "active' states, so you can add a automation that sends MQTT state of the sensor on any change: 

```
alias: 'MQTT Sensors'
description: ''
trigger:
  - entity_id: sensor.main_door
    platform: state
condition: []
action:
  -  data_template:
      topic: '/home/sensor/{{ trigger.entity_id }}'
      payload: '{{ trigger.to_state.state }}'
      retain: true
    service: mqtt.publish
mode: single
```

**Comment by thanksmister** [comment]
This is the PR that @derekatkins tried to do which includes all the updates: ttps://github.com/home-assistant/core/pull/40973

**Comment by thanksmister** [comment]
This is my MQTT for the new weather in the new app: 

```
alias: MQTT Weather
trigger:
  - minutes: /15
    platform: time_pattern
condition: []
action:
  - data:
      payload_template: >-
        {'weather':{'condition':'{{states.weather.home.state}}','humidity':{{states.weather.home.attributes.humidity}},'temperature':{{states.weather.home.attributes.temperature}},'forecast':{{states.weather.home.attributes.forecast}}}}
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
mode: single
```
