### ISSUE TITLE
Play sound via MQTT command

### ISSUE THREAD

**Issue by rogert1** [thanksmister/android-mqtt-alarm-panel#152]
It would be nice to trigger a sound on the android device via an MQTT command.   I would use this for a 'door has been opened' chime. 

I currently use a piezo buzzer and the sound is ugly.   An android would be capable of playing wav, mp3, or other sound file.

**Comment by BoneheadFraggle** [comment]
Do you mean a local file on the device?

If an URL is ok, then it is already possible. I use this example for alarm state change confirmation. 

```
  - service: mqtt.publish
    data:
      payload: '{"audio": "https://your_url/2_fast_beep.mp3"}'
      topic: wallpanel/myandroidphone/command
````

**Comment by rogert1** [comment]
> Do you mean a local file on the device?
> 
> If an URL is ok, then it is already possible. I use this example for alarm state change confirmation.
> 
> ```
>   - service: mqtt.publish
>     data:
>       payload: '{"audio": "https://your_url/2_fast_beep.mp3"}'
>       topic: wallpanel/myandroidphone/command
> ```

Local either in HA or on the android device.   Is the URL sample you used assuming the mp3 is in HA?

Also, is this possible in MQTT Alarm Panel?  I only ask because your topic is for wallpanel, which I am not using.

**Comment by BoneheadFraggle** [comment]
It works in Alarm Panel as well. 
Read more here: https://github.com/thanksmister/android-mqtt-alarm-panel#mqtt-commands

The URL can be whatever, as long as it is reachable from the device. 
Just change the topic to what maches your setup. From what I remember, the default is alarmpanel/command .

If I remember correctly, and if you save the MP3 file in HA /config/www/audio, you could probably use it like this:
```
  - service: mqtt.publish
    data:
      payload: '{"audio": "https://yourHAaddress/local/audio/2_fast_beep.mp3"}'
      topic: alarmpanel/command 

```
