### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jncanches** [thanksmister/android-mqtt-alarm-panel#178]
**Describe the bug**
Weather is not displayed

**To Reproduce**
Set the weather to be displayed. I made tons of tests. I'm sure that the MQTT message is well formatted and published on my MQTT broker. 
Is there something changed with this ? maybe I am missing something...

**Smartphone (please complete the following information):**
 - Device: Samsung GT-P5110
 - OS: Android 7 Lineage OS 14
 - Applicaiton version [app > settings > version] v 1.1.2 build0

**Comment by thanksmister** [comment]
You need to post your MQTT message or automation that publishes weather.   The weather has changed because now we use the generic weather integration.  But the documentation has been updated with examples.

**Comment by jncanches** [comment]
I am using the the payload_template described in documentation.

{''weather'':{''condition'':''{{states.weather.home.state}}'',''humidity'':{{states.weather.home.attributes.humidity}},''temperature'':{{states.weather.home.attributes.temperature}},''forecast'':{{states.weather.home.attributes.forecast}}}}

And I am using the Meteorologisk institutt (Met.no) integration (I think it the default one).

**Comment by thanksmister** [comment]
Have you tried to use the HA dev tools to evaluate this and see that it works?   Also in the MQTT configuration there is a tool to subscribe to the weather to see what is being broadcast.   I don't see any other issues with weather, I am assuming it's on your end perhaps.

**Comment by thanksmister** [comment]
I was not able to reproduce this and no others have reported issues with weather.   Maybe bad formatted MQTT message, you can check the logs in the setting section of the app.

**Comment by ggoodell2** [comment]
i have two tablets running the alarm panel. one shows weather and the other doesnt...

**Comment by thanksmister** [comment]
Not seen this issue on any of my test devices.   Check the logs in the settings to see that the tablets are receiving the weather information and that they are subscribed to the correct event in the settings.

**Comment by erte1** [comment]
I have a similar issue in that 1.0.1 is receiving the weather and sun mqtt just fine, but not receiving 1.1.2.  Maybe it is the topic, but the topic setting screen has changed from 1.01 to 1.1.2 and I'm not clear on which topic setting monitors sun/weather in 1.1.2.

**Comment by thanksmister** [comment]
I think the most likely issue is quotes in the MQTT message, which cause parsing errors for the JSON.   If you need help with the sun/weather, check the wiki for examples.

**Comment by thanksmister** [comment]
This is my weather YAML for Home Assistant:

```
alias: MQTT Weather
trigger:
  - minutes: /15
    platform: time_pattern
condition: []
action:
  - data:
      payload_template: >-
        {'weather':{'condition':'{{states.weather.home.state}}','humidity':{{states.weather.home.attributes.humidity}},'temperature':{{states.weather.home.attributes.temperature}},'forecast':{{states.weather.home.attributes.forecast}}}}
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
mode: single
```

This is my sun YAML:

```
alias: MQTT Sun
trigger:
  - minutes: /30
    platform: time_pattern
condition: []
action:
  - data:
      payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
mode: single
```
