### ISSUE TITLE
Current status doesn't update

### ISSUE THREAD

**Issue by alex-savin** [thanksmister/android-mqtt-alarm-panel#22]
Hi,

I have an issue with status update.
I can Arm the system and everything is fine, I see in Hass everything updated, and in App status get changed to Armed.
But when I Disarm the system, it got disarmed in the Hass, but App stays in Armed state.
I tried on two devices (Kindle Fire HD 8 and Google Pixel 2 XL), the same result.
How I can fix it?!

Thank you in advance

**Comment by alex-savin** [comment]
@thanksmister 
```
alarm_control_panel:
  - platform: manual_mqtt
    name: alarm
    state_topic: "hass/alarm"
    command_topic: "hass/alarm/set"

    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30

    payload_disarm: DISARM
    payload_arm_home: ARM_HOME
    payload_arm_away: ARM_AWAY
    payload_available: online
    payload_not_available: offline
```

**Comment by thanksmister** [comment]
Make aure these are set within the application as well, they need to be identical under the MQTT settings 

state_topic: "hass/alarm"
 command_topic: "hass/alarm/set

**Comment by thanksmister** [comment]
You don’t need to set these just use the defaults by removing them from the configuration file:

payload_disarm: DISARM
    payload_arm_home: ARM_HOME
    payload_arm_away: ARM_AWAY
    payload_available: online
    payload_not_available: offline

**Comment by thanksmister** [comment]
It’s  something out of sync with your MQTT settings and what you set in the application.  It’s hard for me to determine the issue since you’ve setup what you have. Just be sure the application MQTT settings are matching what is in HASS.

**Comment by alex-savin** [comment]
These all my settings

HASS
```
  - platform: manual_mqtt
    name: alarm
    state_topic: "hass/alarm"
    command_topic: "hass/alarm/set"

    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30

    payload_disarm: DISARM
    payload_arm_home: ARM_HOME
    payload_arm_away: ARM_AWAY
    payload_available: online
    payload_not_available: offline
```

Android App
![android_mqtt_control_panel](https://user-images.githubusercontent.com/10366351/39680893-c80efec6-5173-11e8-868c-7799b83c5d26.jpg)

and the log from Mosquito
```
hass/alarm disarmed
hass/alarm/set ARM_HOME
hass/alarm/set DISARM
hass/alarm/set DISARM
hass/alarm/set ARM_HOME
hass/alarm armed_home
hass/alarm/set DISARM
hass/alarm disarmed
hass/alarm/set ARM_AWAY
hass/alarm pending
hass/alarm armed_away
hass/alarm/set DISARM
hass/alarm disarmed
hass/alarm/set DISARM
hass/alarm/set DISARM
hass/alarm armed_home
hass/alarm disarmed
hass/alarm pending
hass/alarm armed_away
```

Interesting that Android App sends commands in UPPER case, but Hass sends in LOWER case
Could the upper/lower case be an issue, that Android App doesn't sync with MQTT server?!
