### ISSUE TITLE
Can't get weather and day/night mode working in latest version 

### ISSUE THREAD

**Issue by mjsambol** [thanksmister/android-mqtt-alarm-panel#92]
Hi thank you for this great app!

Since the changes in the latest version I am not able to get the app to show weather or change day/night mode.

I've set up rules following your examples and have tried manually sending MQTT messages in developer tools. The app seems to be working fine in all other respects, but I can not get these features to work. It's as if the messages are never received by the tablet.

I found the log book, and it shows other messages. I have no problem with 'speak':'hello'. But weather and sun - nothing.

Here are my actions:

```
automation publish_sun_status:
  - alias: MQTT Sun
    trigger:
      platform: time_pattern
      minutes: '/15'
    action:
      service: mqtt.publish
      data:
        payload_template: '{''sun'':''''}'
        retain: true
        topic: alarmpanel/command
  - alias: MQTT Weather
    trigger:
      platform: time_pattern
      minutes: '/30'
    action:
      service: mqtt.publish
      data:
        payload_template: '{''weather'':}'
        retain: true
        topic: alarmpanel/command
```

help?

**Comment by thanksmister** [comment]
These are from my automation files, I used the automation creation tool to make them 

```
- id: '1538595661244'
  alias: MQTT Weather
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''weather'':{{states.weather.dark_sky.attributes}}}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
- id: '1539017708085'
  alias: MQTT Sun
  trigger:
  - minutes: /30
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish```

**Comment by thanksmister** [comment]
<img width="796" alt="mqtt_weather" src="https://user-images.githubusercontent.com/142340/55594332-95c29d80-5715-11e9-91f8-3c21ab7c9259.png">

**Comment by thanksmister** [comment]
<img width="687" alt="sun_mqtt1" src="https://user-images.githubusercontent.com/142340/55594646-d1119c00-5716-11e9-8ef1-d07a52b9ed32.png">
<img width="743" alt="sun_mqtt2" src="https://user-images.githubusercontent.com/142340/55594647-d1119c00-5716-11e9-9893-845a97266934.png">

**Comment by thanksmister** [comment]
Make sure these are set in your configuration.yaml file:

```
# Track the sun
sun:
```
```
# Weather with darksky 
weather:
  - platform: darksky
    api_key: [redacted]
```
